### ISSUE TITLE
ClassNotFoundException: com.sun.xml.bind.api.ErrorListener

### ISSUE THREAD

**Issue by johny65** [eclipse-ee4j/metro-jax-ws#103]
I need the `wsimport` tool and the only thing I could find that seems updated to Java 11 is the [jaxws-ri-2.3.1.zip](https://repo1.maven.org/maven2/com/sun/xml/ws/jaxws-ri/2.3.1/jaxws-ri-2.3.1.zip) file.

But when I run the wsimport.sh script it fails with java.lang.ClassNotFoundException: com.sun.xml.bind.api.ErrorListener. This is the stacktrace:

````
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/xml/bind/api/ErrorListener
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getConstructor0(Class.java:3342)
	at java.base/java.lang.Class.getConstructor(Class.java:2151)
	at com.sun.tools.ws.Invoker.invoke(Invoker.java:150)
	at com.sun.tools.ws.WsImport.main(WsImport.java:56)
Caused by: java.lang.ClassNotFoundException: com.sun.xml.bind.api.ErrorListener
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 24 more
````

I'm running it in Ubuntu 19.10 with Java 11 (openjdk version "11.0.6" 2020-01-14).

**Comment by evandropomatti** [comment]
Same problem running on Windows.

**Comment by lukasj** [comment]
can you try https://repo1.maven.org/maven2/com/sun/xml/ws/jaxws-ri/2.3.3-b01/jaxws-ri-2.3.3-b01.zip and let me know what does not work there? Latest final release is currently 2.3.2, not 2.3.1

**Comment by johny65** [comment]
@lukasj It seems to work fine with that version (2.3.3-b01), thanks.

When I searched for the download, I could only find the link to 2.3.1 version (from [here](https://javaee.github.io/metro-jax-ws/)), where is the 2.3.2 version published?

**Comment by lukasj** [comment]
everything gets published to maven, for zip distribution, see https://repo1.maven.org/maven2/com/sun/xml/ws/jaxws-ri/

javaee page is obsolete, I hope I get to provide the web for this soon at https://eclipse-ee4j.github.io/metro-jax-ws/ , should you be looking for the user guide, it is available also at https://eclipse-ee4j.github.io/metro-wsit/

**Comment by mfplunet** [comment]
I am having the same problem from the eclipse-ee4j.github.io link with version 4.0.0. Openjdk 17.0.13
