### ISSUE TITLE
OSGi classloading issue with "com.sun.xml.ws.runtime.config.ObjectFactory.class"

### ISSUE THREAD

**Issue by malm66** [eclipse-ee4j/metro-jax-ws#128]
Trying to port an existing Eclipse RCP application to Java 11 using the latest jaxws-rt (2.3.3) and jaxb-impl (2.3.3) bundles. These bundles and their dependencies are added to the target platform as we have multiple plugins that require JAXB and JAX-WS.

Problem is that jaxws cannot read it's config file due to classloading issues as per the below stacktrace. It appears that jaxws at `com.sun.xml.ws.assembler.MetroConfigLoader.createJAXBContext()` is calling `javax.xml.bind.JAXBContext.newInstance()` without providing a classloader. Therefore `javax.xml.bind.JAXBContext` passes it's own ContextClassLoader down the call chain. Hower, that classloader can't find `com.sun.xml.ws.runtime.config.ObjectFactory` .

`
Caused by: javax.xml.bind.JAXBException: "com.sun.xml.ws.runtime.config" doesnt contain ObjectFactory.class or jaxb.index
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:260)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:171)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:313)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:478)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:435)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:336)
	at com.sun.xml.ws.assembler.MetroConfigLoader.createJAXBContext(MetroConfigLoader.java:268)
	at com.sun.xml.ws.assembler.MetroConfigLoader.loadMetroConfig(MetroConfigLoader.java:226)
`

**Comment by lukasj** [comment]
My knowledge wrt Eclipse RCP is very limited, so unless there is either a simple test case OR reproducible app attached/referenced I cannot do much. Also does using jaxb.properties help?

**Comment by lukasj** [comment]
btw does the problem happens also with [webservices-osgi.jar](https://repo1.maven.org/maven2/org/glassfish/metro/webservices-osgi/2.4.4/) ?

**Comment by malm66** [comment]
Going down the webservices-osgi path causes another set of missing dependencies

![image](https://user-images.githubusercontent.com/32324397/81031042-7c15fb80-8ebd-11ea-8ba7-89b42ff8c1ef.png)

**Comment by malm66** [comment]
By wrapping my code that sets up the webservices port with the code below fixes the ClassNotFoundError. That piece of code explicitly sets the ContextClassLoader to the classloader used for the Metro Config class. This seems to indicate that default ContextClassLoader used by jaxb when no classloader is provided is not finding classes in jaxws-rt.

`
    final Thread thread = Thread.currentThread();
    final ClassLoader oldLoader = thread.getContextClassLoader();
    try {
        thread.setContextClassLoader(MetroConfig.class.getClassLoader());
        final String endpointAddress = ServiceLocator.getConfigService()
            .findValue(ConfigKey.SERVER_MANAGER_ENDPOINT_URL);
        return PortFactory.getPort(...);
    } finally {
        thread.setContextClassLoader(oldLoader);
    }
`

**Comment by malm66** [comment]
The more I read about OSGi class loading the more I got the feeling that the current jaxb-ri and jaxws-rt will never "co-operate" as they are not coupled through the OSGi wiring. Code in jaxws-ri cannot instantiate classes in jaxws-rt through Class.forName or similar mechanism. OSGi simply doesn't allow this. Of course in Java 8 that all worked as all these classes lived together in rt.jar.

I really hope I am wrong but for now I will have to wrap all calls that instantiate web services with code similar to the above.

**Comment by lukasj** [comment]
GlassFish is an OSGi container and webservices-osgi + jaxb-osgi (+relevant dependencies) do work well together there, relevant APIs are not those coming from JDK but those coming with standalone metro versions. Also note that classes in JDK and in standalone implementation are different. The difference might by also in the OSGi framework in use and its setup - as I said, without something I can easily play with, it is hard to help.

**Comment by malm66** [comment]
@lukasj I have put together a sample Eclipse RAP project with sources, target platform, and Eclipse workspace that demonstrates the problem. However, it is too big to attach (140MB). How can I get that to you?

**Comment by lukasj** [comment]
one option would be to create github repo, another to use some file sharing service like google drive, dropbox, whatever

**Comment by malm66** [comment]
File is in [DropBox](https://www.dropbox.com/s/hhqfpvq0uk7kuvn/webservices_issue.zip?dl=0)

You need to have the [Eclipse IDE for RCP and RAP](https://www.eclipse.org/downloads/packages/release/2020-03/r/eclipse-ide-rcp-and-rap-developers)  installed.

Expand the ZIP, start the IDE with the workspace being the workspace folder provided in the ZIP. You probably will have to configure the Java Runtime setting in the Eclipse IDE to match your environment. Run or Debug the application using the configured "RAP Application". This should open a browser window (may need one refresh) and click the single button shown. That should produce the error.

**Comment by malm66** [comment]
BTW, this problem is not specific to the Metro Config. It appears any call to `JAXBContext newInstance( String contextPath )` has that problem. The ContextClassLoader provided by the Eclipse OSGi environment cannot find the `contextPath + ".ObjectFactory"` class as it is in a bundle not visible to the jaxb-ri bundle.

**Comment by col-panic** [comment]
@malm66  I could solve loading JAXB on Java 11 OSGi by using a fragment bundle (see https://github.com/elexis/elexis-3-core/tree/master/bundles/jaxb-api-impl-import-java9) It manually adds the `import package` to `jaxb-api` - not sure whether this fully fits, but it might be a hint

**Comment by malm66** [comment]
@col-panic Thanks for the hint but I think my problem is different. Your solution made jaxb-impl visible to jaxb-api so it could find the implementation. BTW, this doesn't seem necessary anymore as that part works now. My problem is that the jaxb-impl bundle calls `classLoader.loadClass(<my package name> +".ObjectFactory")` but there is no OSGi wiring that connects my bundle to the jaxb-impl bundle. My bundle only knows about jaxb-api and has no idea how it is implemented. Now in my bundles I can work around this by using the JAXBContext.newInstance("<my package name>", classLoader) API with classLoader being the classloader associated with "my package name". However, the jaxws-ri bundle, over which I have no control, invokes just  `JAXBContext.newInstance("com.sun.xml.ws.runtime.config")`. With no OSGi wiring between the jaxws-ri and jaxb-impl bundles, jaxb-impl cannot load the `com.sun.xml.ws.runtime.config.ObjectFactory` class using the classloader it has been given when invoked via the jaxb-api bundle. That classloader is the default ContextClassLoader `org.eclipse.osgi.internal.framework.ContextFinder` the Eclipse OSGi framework injects. See [here](https://wiki.eclipse.org/Context_Class_Loader_Enhancements) for a description of how this classloader works.

**Comment by col-panic** [comment]
As found in https://www.eclipse.org/lists/jaxws-dev/msg00015.html - I just tried the entire org.glassfish.metro.webservices-osgi chain. Yet it fails to run - it's like starting from the beginning, it can't resolve the service implementation

```
java.lang.NullPointerException: null
	at javax.xml.ws.Service.<init>(Service.java:82) ~[na:na]
	at ch.curabill.services.invoices.InvoicesSOAPService.<init>(InvoicesSOAPService.java:45) ~[na:na]
	at at.medevit.elexis.curabill.core.InvoicesClient.submitInvoice(InvoicesClient.java:196) ~[na:na]
```

`jakarta.xml.bind-api` does not work in the OSGI environment without my additional fragment. If i remove it I get the familiar

```
Caused by: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory]
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:232)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:375)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:632)
	at org.glassfish.jersey.jaxb.internal.AbstractJaxbProvider.getStoredJaxbContext(AbstractJaxbProvider.java:311)
	at org.glassfish.jersey.jaxb.internal.AbstractJaxbProvider.getJAXBContext(AbstractJaxbProvider.java:296)
	at org.glassfish.jersey.jaxb.internal.AbstractJaxbProvider.getUnmarshaller(AbstractJaxbProvider.java:212)
	at org.glassfish.jersey.jaxb.internal.AbstractJaxbProvider.getUnmarshaller(AbstractJaxbProvider.java:187)
	at org.glassfish.jersey.jaxb.internal.AbstractRootElementJaxbProvider.readFrom(AbstractRootElementJaxbProvider.java:134)
	... 114 more
Caused by: java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.eclipse.osgi.internal.framework.ContextFinder.loadClass(ContextFinder.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at javax.xml.bind.ServiceLoaderUtil.nullSafeLoadClass(ServiceLoaderUtil.java:92)
	at javax.xml.bind.ServiceLoaderUtil.safeLoadClass(ServiceLoaderUtil.java:125)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:230)
	... 122 more
```

at least I have this solution for JAXB - but JAXWS drives me nuts. It seems like I will have to cancel the transition to Java 11 for some more years?!

**Comment by malm66** [comment]
@col-panic I am not sure what your problem is. For me the jaxb-api / jaxb-impl combination works in the sense that the API finds the implementation without problems. When it comes to initialising any JAXB context though it doesn't work. For my classes I need to pass the relevant class loader into the JAXBContext.newInstance API. And to make jaxws work I have to set the ContextClassLoader before invoking the service. I haven't tried the webservices jar's yet nor when we are the endpoint provider of a webservice. And yes, migrating to Java 11 with jaxb and jaxws is clearly a nightmare in an Eclipse OSGi environment. I tried around the same time last year without success. Getting further this time but it not a done deal yet.

**Comment by lukasj** [comment]
@malm66 thanks for the app, I managed to reproduce your problem. I'll try to play with it over the next few days...

**Comment by lukasj** [comment]
@col-panic note that in you case it is jersey and not jax-ws who is calling jaxb:

```
[java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory]
...
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:632)
	at org.glassfish.jersey.jaxb.internal.AbstractJaxbProvider.getStoredJaxbContext(AbstractJaxbProvider.java:311)
...
```
 so your problem can be different. Maybe if you put together some reproducer and deliver it to me somehow, I could take a look. Without that it's mostly guessing....

**Comment by col-panic** [comment]
I'm using jersey to implement a jax-rs interface (we forked osgi-jax-rs-connector from holger staudacher in https://github.com/MEDEVIT/osgi-jax-rs-connector). It packs an entire jersey into a single distribution plugin, but uses the available jaxb.

I tried to break-up this packed plugin, manually adding each jersey bundle to the osgi container, but all this hk2 osgi-locator stuff simply does not work right in Eclipse equinox. To many modifications and interdependencies on whatever side (MessageBodyReaders that stop being found etc.)

Frankly I don't grasp all that stuff anymore. Without those libraries being available as they were, I can't seem to get the app running like it was with Java 8. Try to sell a customer the need to switch to Java 11 and explain that you can't (with newer tech) get stuff running that worked ...

I'm stopping this for the moment being - we will stay with Java 8 for quite some time longer ... thx for the help!

**Comment by col-panic** [comment]
I think we would have to setup up and equinox based application that does use all of the services that were removed with Java 11. Either containing multi-release and/or "native" Java 11 / 8 bundles. Then the unit tests would have to be executed both Java 8 and 11. I guess this would also help a lot of people when it comes to migrating such an application (cf. the mailinglist Eclipse RCP entry)

**Comment by malm66** [comment]
@lukasj The essentially same problem happens when publishing a webservice endpoint
```

com.sun.xml.ws.model.RuntimeModelerException: class: au.net.synergy.wts.application.server.manager.ServerManager could not be found
	at com.sun.xml.ws.model.RuntimeModeler.getPortTypeName(RuntimeModeler.java:1589)
	at com.sun.xml.ws.model.RuntimeModeler.getPortTypeName(RuntimeModeler.java:1572)
	at com.sun.xml.ws.server.EndpointFactory.create(EndpointFactory.java:227)
	at com.sun.xml.ws.server.EndpointFactory.createEndpoint(EndpointFactory.java:134)
	at com.sun.xml.ws.api.server.WSEndpoint.create(WSEndpoint.java:548)
	at com.sun.xml.ws.api.server.WSEndpoint.create(WSEndpoint.java:530)
	at com.sun.xml.ws.transport.http.server.EndpointImpl.createEndpoint(EndpointImpl.java:304)
	at com.sun.xml.ws.transport.http.server.EndpointImpl.publish(EndpointImpl.java:227)
	at au.net.synergy.wts.application.server.http.HttpService.publishEndpoint(HttpService.java:179)
```
It does look different but the root cause is the same as `RuntimeModeler.getPortTypeName()` is using the context class loader `clazz = Thread.currentThread().getContextClassLoader().loadClass(epi);` to find the interface. And in an (Equinox) OSGi environment that simply won't work. The initial workaround is the same as mentioned before: Fudge the ContextClassLoader to be a classloader that can the see webservice interface class. However, that simple fudge is not enough as then we are back to the proper originally reported problem that the Metro config can't be found. So the final workaround is to inject a custom class loader as the ContextClassLoader that can load both the Metro config and my webservice interface class.

Just out of curiosity I checked where else getContextClassLoader() is used in the jaxws-rt file and it comes up a lot. I am really wondering how many more of those issues I will run into.

```
com.sun.xml.ws.db.DatabindingFactoryImpl.classLoader()
com.sun.xml.ws.transport.httpspi.servlet.WSSPIContextListener.contextInitialized(ServletContextEvent)
com.sun.xml.ws.util.xml.XmlCatalogUtil.createDefaultCatalogResolver()
com.sun.xml.ws.client.Stub.createPipeline(WSPortInfo, WSBinding)
com.sun.xml.ws.api.pipe.ClientTubeAssemblerContext.createTransportTube()
com.sun.xml.ws.util.ServiceFinder.find(Class<T>, Component)
com.sun.xml.ws.util.ServiceFinder.find(Class<T>)
com.sun.xml.ws.model.RuntimeModeler.getClass(String, Localizable)
com.sun.xml.ws.util.HandlerAnnotationProcessor.getClass(String)
com.sun.xml.ws.model.RuntimeModeler.getPortTypeName(Class<?>, String, MetadataReader)
com.sun.xml.ws.model.RuntimeModeler.getRequestWrapperClass(String, Method, QName)
com.sun.xml.ws.util.MrJarUtil.getResourceAsStream(Class, String)
com.sun.xml.ws.model.RuntimeModeler.getResponseWrapperClass(String, Method, QName)
com.sun.xml.ws.assembler.TubelineAssemblyController.initializeTubeCreators(TubeFactoryList)
com.sun.xml.ws.assembler.MetroConfigLoader.MetroConfigUrlLoader.loadViaClassLoaders(String)
com.sun.xml.ws.api.addressing.NonAnonymousResponseProcessor.process(Packet)
com.sun.xml.ws.api.streaming.new PrivilegedAction() {...}.run()
com.sun.xml.ws.commons.xmlutil.new PrivilegedAction() {...}.run()
com.sun.xml.ws.developer.new PrivilegedAction() {...}.run()
com.sun.xml.ws.spi.new PrivilegedAction() {...}.run()
com.sun.xml.ws.util.xml.new PrivilegedAction() {...}.run()
com.sun.xml.ws.server.WSEndpointImpl.WSEndpointImpl(QName, QName, WSBinding, Container, SEIModel, WSDLPort, Class<T>, ServiceDefinitionImpl, EndpointAwareTube, boolean, PolicyMap)
com.sun.xml.ws.client.WSServiceDelegate.WSServiceDelegate(Source, WSDLService, QName, Class<? extends Service>, WebServiceFeatureList)
```

**Comment by lukasj** [comment]
@malm66 the thing here is that most of these are used in a (app) server environment, which has different requirements than osgi wrt classloading

**Comment by malm66** [comment]
@lukasj Not so sure about that claim. The jax-rs reference implementation `org.glassfish.jersey` had to deal with the same problem and they have written code to handle this. See `org.glassfish.jersey.internal.OsgiRegistry`. So jax-rs is fine but the jax-ws reference implementation is not. And both are used in app servers as well as client applications. Yes I know, different heritage, and jax-rs is more recent and was never part of the JDK. Still I think it would be desirable for the jax-ws and jaxb reference implementations to work in the Equinox OSGi environment which after all is another Eclipse product.

**Comment by lukasj** [comment]
> @lukasj Not so sure about that claim. The jax-rs reference implementation `org.glassfish.jersey` had to deal with the same problem and they have written code to handle this. 

was that part of JDK as well?

**Comment by vogella** [comment]
I'm running into the same problem. Did anymore manage to solve this issue?

Caused by: javax.xml.bind.JAXBException: "com.sun.xml.ws.runtime.config" doesnt contain ObjectFactory.class or jaxb.index
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:263)

**Comment by vogella** [comment]
I used the trick mentioned by @malm66 and run the code with the context class loader that seems to work.


	@Execute
	public void execute() {
		// starting a webservice
		System.setProperty("jakarta.xml.soap.SAAJMetaFactory", "com.sun.xml.messaging.saaj.soap.SAAJMetaFactoryImpl");
		System.setProperty("javax.xml.soap.SAAJMetaFactory", "com.sun.xml.messaging.saaj.soap.SAAJMetaFactoryImpl");
		String url = "http://localhost:4437/miniwebservice";

		ClassLoader tccl = Thread.currentThread().getContextClassLoader();
		Thread.currentThread().setContextClassLoader(this.getClass().getClassLoader());
		try {
			javax.xml.ws.Endpoint.publish(url, new WebServiceExample());
		} finally {
			Thread.currentThread().setContextClassLoader(tccl);
		}
	}


I pushed my example to https://github.com/vogellacompany/eclipsercp-javaws-java11 is case someone wants to replicate this.

**Comment by laeubi** [comment]
> With no OSGi wiring between the jaxws-ri and jaxb-impl bundles, jaxb-impl cannot load the `com.sun.xml.ws.runtime.config.ObjectFactory` class using the classloader it has been given when invoked via the jaxb-api bundle. 

This usually is one of the cases where `Dynamic-Import-Package` should/could be used as in general there is no way to know in advance the packages to load.
