### ISSUE TITLE
Client stub generated using wsimport v3 trying to connect to port 80 while provided URL is https.

### ISSUE THREAD

**Issue by KrishnaST** [eclipse-ee4j/metro-jax-ws#230]
Java Version : 11
JaxWs RT Version :3.0.1
Test URL : https://aepstest.fssnet.co.in/CSB_EMV_Services_SIT/Services/CSB_Service.asmx?wsdl

Attached : Sample Project, Wireshark Trace, Log containing TCP and HTTP Trace.
[tcp & http trace.log](https://github.com/eclipse-ee4j/metro-jax-ws/files/6553461/tcp.http.trace.log)
[Sample Project.zip](https://github.com/eclipse-ee4j/metro-jax-ws/files/6553462/Sample.Project.zip)
[Wireshark.zip](https://github.com/eclipse-ee4j/metro-jax-ws/files/6553468/Wireshark.zip)

```
com.sun.xml.ws.client.ClientTransportException: HTTP transport error: java.net.ConnectException: Connection timed out: connect
	at com.sun.xml.ws.transport.http.client.HttpClientTransport.getOutput(HttpClientTransport.java:104)
	at com.sun.xml.ws.transport.http.client.HttpTransportPipe.process(HttpTransportPipe.java:197)
	at com.sun.xml.ws.transport.http.client.HttpTransportPipe.processRequest(HttpTransportPipe.java:124)
	at com.sun.xml.ws.transport.DeferredTransportPipe.processRequest(DeferredTransportPipe.java:80)
	at com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:1106)
	at com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:1020)
	at com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:989)
	at com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:847)
	at com.sun.xml.ws.client.Stub.process(Stub.java:433)
	at com.sun.xml.ws.client.sei.SEIStub.doProcess(SEIStub.java:161)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:78)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:62)
	at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:131)
	at com.sun.proxy.$Proxy33.transactionRequest(Unknown Source)
	at com.test.ws.Application.main(Application.java:26)
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1242)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1221)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1075)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1009)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1356)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1331)
	at com.sun.xml.ws.transport.http.client.HttpClientTransport.getOutput(HttpClientTransport.java:91)
	... 14 more
```

**Comment by KrishnaST** [comment]
![image](https://user-images.githubusercontent.com/9427954/119885364-5f78b580-bf4f-11eb-91f3-67a14a94c711.png)

**Comment by KrishnaST** [comment]
I got why this is happening. Though the provided **https** URL to Service class the wsdl file at that location contains http URL in location attribute of soap12:address tag.  I am not sure though what is expected to happen in this kind of scenario.
![image](https://user-images.githubusercontent.com/9427954/119893390-ebdba600-bf58-11eb-8d6d-beb050220212.png)

![image](https://user-images.githubusercontent.com/9427954/119892805-33156700-bf58-11eb-9196-603c088015f5.png)

**Comment by lukasj** [comment]
the service URL in the WSDL points to http which is then redirected. In this case, one has to use `BindingProvider.ENDPOINT_ADDRESS_PROPERTY`, ie following call succeeds: 

```java
CSBService s = new CSBService();
CSBServiceSoap svc = new CSBService().getCSBServiceSoap();
((BindingProvider) svc).getRequestContext().put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY, "https://aepstest.fssnet.co.in/CSB_EMV_Services_SIT/Services/CSB_Service.asmx");
```
