### ISSUE TITLE
NPE in EndpointArgumentsBuilder with complex class hierarchy

### ISSUE THREAD

**Issue by UKreher** [eclipse-ee4j/metro-jax-ws#44]
We have a class hierarchy similar to the attached file [ClsHier.zip](https://github.com/eclipse-ee4j/metro-jax-ws/files/2988395/ClsHier.zip). It is rather complex but this is due to having classes for REST and SOAP and sharing some the code.
When creating the endpoint, the following NPE occurs:

`Caused by: java.lang.NullPointerException
	at com.sun.xml.ws.server.sei.EndpointArgumentsBuilder$DocLit.<init>(EndpointArgumentsBuilder.java:548)
	at com.sun.xml.ws.server.sei.TieHandler.createArgumentsBuilder(TieHandler.java:113)
	at com.sun.xml.ws.server.sei.TieHandler.<init>(TieHandler.java:85)
	at com.sun.xml.ws.db.DatabindingImpl.<init>(DatabindingImpl.java:89)
	at com.sun.xml.ws.db.DatabindingProviderImpl.create(DatabindingProviderImpl.java:44)
	at com.sun.xml.ws.db.DatabindingProviderImpl.create(DatabindingProviderImpl.java:28)
	at com.sun.xml.ws.db.DatabindingFactoryImpl.createRuntime(DatabindingFactoryImpl.java:90)
	at com.sun.xml.ws.server.EndpointFactory.createSEIModel(EndpointFactory.java:491)
	at com.sun.xml.ws.server.EndpointFactory.create(EndpointFactory.java:270)
	at com.sun.xml.ws.server.EndpointFactory.createEndpoint(EndpointFactory.java:134)
	at com.sun.xml.ws.api.server.WSEndpoint.create(WSEndpoint.java:548)
	at com.sun.xml.ws.api.server.WSEndpoint.create(WSEndpoint.java:530)
	at com.sun.xml.ws.transport.http.DeploymentDescriptorParser.parseAdapters(DeploymentDescriptorParser.java:273)
	at com.sun.xml.ws.transport.http.DeploymentDescriptorParser.parse(DeploymentDescriptorParser.java:149)`

The problem is that `AbstractSEIModelImpl.xmlBridgeMap` contains an instance of `TypeInfo` that has the `WrapperParameter` for `ws.iface.IFace.getSomeObject()` in the properties. But the instance of `WrapperParameter` provided to the constructor of `DocLit` stems from `ws.soap.iface.IFace.getSomeObject()`. Both wrapper parameter refer to the same but since `TypeInfo` does not implement a specific `equals(Object)` `AbstractSEIModelImpl.getXMLBridge(TypeInfo)` returns `null` leading to the above exception.

**Comment by jbescos** [comment]
@UKreher I am not able to reproduce the issue with your example. Maybe you can take a look to my test if you want:
https://github.com/jbescos/metro-jax-ws/commit/68f6e395ed91e0eb3db00a3b33433f9d7912c8f3
You will find your example here:  jaxws-ri/tests/unit/testcases/fromjava/hierarchy

To execute the tests you can do the next:
- git clone https://github.com/jbescos/metro-jax-ws.git
- cd metro-jax-ws
- git checkout origin/issue44 
- mvn clean install

Then you can run the tests in the next folder jaxws-ri/tests/unit/testcases with mvn clean install
