### ISSUE TITLE
webservices-osgi-2.4.3 class not found com/sun/org/apache/xml/internal/resolver/CatalogManager

### ISSUE THREAD

**Issue by malm66** [eclipse-ee4j/metro-jax-ws#50]
When trying to use webservices-osgi-2.4.3 in an Eclipse RCP application under Java 11 I get the  following NoClassDefFoundError:

Caused by: java.lang.NoClassDefFoundError: com/sun/org/apache/xml/internal/resolver/CatalogManager
	at com.sun.xml.ws.util.xml.XmlUtil.createDefaultCatalogResolver(XmlUtil.java:296)
	at com.sun.xml.ws.client.WSServiceDelegate.createCatalogResolver(WSServiceDelegate.java:348)
	at com.sun.xml.ws.client.WSServiceDelegate.parseWSDL(WSServiceDelegate.java:334)
	at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:292)
	at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:201)
	at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:182)
	at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:178)
	at com.sun.xml.ws.spi.ProviderImpl.createServiceDelegate(ProviderImpl.java:89)
	at javax.xml.ws.Service.<init>(Service.java:82)
	at au.net.synergy.wts.server.ws.client.management.ServerManagerImplService.<init>(ServerManagerImplService.java:47)

This class has been removed from the JDK since Java 10 but is referenced by com.sun.xml.ws.util.xml.XmlUtil. 

How can I make this work?

**Comment by bravehorsie** [comment]
Looks like `webservices-osgi` repackaging doesn't honor `com.sun.xml.ws:rt` dependency mr-jar based META-INF/versions/9 folder.

**Comment by malm66** [comment]
Interestingly webservices-osgi-2.4.3 is not a mr-jar but webservices-osgi-2.4.3-sources is. But even webservices-osgi-2.4.3-sources doesn't contain the missing classes.

**Comment by malm66** [comment]
Even jaxws-rt-2.3.2 doesn't contain com/sun/org/apache/xml/internal/resolver/CatalogManager in its versions\9 folder. I guess it would have to be a versions\10 folder?

Any way, any ideas on how to work around this problem. Which JAR/Maven artefact does actually contain these classes?

**Comment by lukasj** [comment]
[wsit](https://github.com/eclipse-ee4j/metro-wsit) has not been updated for jdk11 yet. Google finds old version of CatalogManager in [this jar](http://repo1.maven.org/maven2/com/sun/org/apache/xml/internal/resolver/20050927/resolver-20050927.jar)

**Comment by malm66** [comment]
Thanks lukas. Any ETA when the ee4j project will deliver an OSGI compatible full webservices stack that works under Java 11? This is just so I can tell my managers when we are expected to get off Java 8 which is now out of (free) support.

**Comment by bravehorsie** [comment]
@malm66 You are looking at wrong artifact. Its [com.sun.xml.ws:rt](https://repo1.maven.org/maven2/com/sun/xml/ws/rt/2.3.2/) (instead of jaxws-rt). Substitution `CatalogManager` API for removed classes was addes since 9, so versioning folders are correct in that regard.

**Comment by lukasj** [comment]
Clients/end-users should NOT care about internal project structure (represented by `rt` artifact among others); `jaxws-rt` and `jaxws-tools` are supposed to be all they need.

As for the ETA - months timeframe; my wish is May-June (rather sooner than later)

**Comment by malm66** [comment]
As far as I can tell after a quick look com.sun.xml.ws:rt is not an OSGI bundle and does not contain the missing com/sun/org/apache/xml/internal/resolver/CatalogManager and related classes.

Thank lukas for the frank answer. We will delay our move to Java 11 until the ee4j web services stack is ready for consumption in Java 11 OSGI environments (e.g. equinox).

PS: There is still the issue that webservices-osgi-2.4.3 relies on Servlet 4.0 but Eclipse 2019-03 comes with Jetty that requires Servlet 3.0. For reasons I don't understand Equinox was complaining when both the Servlet 3.0 and 4.0 bundles were in the target environment. To get around that problem I edited (yuk,....) the webservices-osgi-2.4.3 manifest to require javax.servlet [3.0.0, 5.0.0). That made Equinox happy but because I didn't get any further with using web services under Equinox/Jetty I am not sure if that would cause runtime issues later.

**Comment by bravehorsie** [comment]
@malm66 There is no `com/sun/org/apache/xml/internal/resolver/CatalogManager` added to jaxws deliverables. It is part of JavaSE prior to 10. What MR-JAR does in this case is either:
 - load `com/sun/org/apache/xml/internal/resolver/CatalogManager` from JavaSE prior to 10
 - load META-INF/versions/9 which uses new API instead of the above on 9 and up.

@lukasj @malm66 I don't ask you to use `com.sun.xml.ws:rt` in a client project, just pointing out that the reported problem is fixed by including META-INF/versions/9 from this artifact during jaxws-rt and webservices-osgi fat-jars generation.

**Comment by malm66** [comment]
@bravehorsie Interesting, are you saying that in a Java 11 environment, with a 'correctly' packaged webservices-osgi it won't invoke com.sun.xml.ws.spi.ProviderImpl but use a different provider and therefore will never try to load com/sun/org/apache/xml/internal/resolver/CatalogManager?

**Comment by bravehorsie** [comment]
@malm66 Yes, so it is meant to behave (given your environment supports [JEP-238](https://openjdk.java.net/jeps/238)). In JAXWS sources you can find [XmlCatalogUtil.java](https://github.com/eclipse-ee4j/metro-jax-ws/blob/master/jaxws-ri/rt/src/main/java/com/sun/xml/ws/util/xml/XmlCatalogUtil.java), which is replaced with [its mr-jar version ](https://github.com/eclipse-ee4j/metro-jax-ws/blob/master/jaxws-ri/rt/src/main/java-mr/9/com/sun/xml/ws/util/xml/XmlCatalogUtil.java). Note that the latter contains no `com.sun.org.apache.xml.internal.*` imports.

**Comment by malm66** [comment]
@bravehorsie Thank you very much for that explanation. Any plans for producing a new mr-jar version of webservices-osgi I could test with?

**Comment by lukasj** [comment]
`com.sun.xml.ws:jaxws-rt` and `com.sun.xml.ws:jaxws-tools` should be valid OSGi bundles now (see eclipse-ee4j/metro-jax-ws#70 )
