### ISSUE TITLE
webservices-rt 2.4.3 is missing org.glassfish.pfl:pfl dependency

### ISSUE THREAD

**Issue by jurajw** [eclipse-ee4j/metro-jax-ws#51]
Hi,

tested on plain Java SE 1.8.0u202 and Java SE 11.0.2.

When publishing an endpoint following stack-trace is logged in WARNING level (and monitoring MBean is not setup):

java.lang.NoClassDefFoundError: org/glassfish/pfl/basic/func/UnaryPredicate
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:264)
at org.glassfish.gmbal.util.GenericConstructor.getConstructor(GenericConstructor.java:58)
at org.glassfish.gmbal.util.GenericConstructor.create(GenericConstructor.java:90)
at org.glassfish.gmbal.ManagedObjectManagerFactory.createStandalone(ManagedObjectManagerFactory.java:77)
at com.sun.xml.ws.server.MonitorBase.createMOM(MonitorBase.java:193)
at com.sun.xml.ws.server.MonitorBase.createMOMLoop(MonitorBase.java:181)
at com.sun.xml.ws.server.MonitorBase.createManagedObjectManager(MonitorBase.java:104)
at com.sun.xml.ws.server.WSEndpointImpl.obtainManagedObjectManager(WSEndpointImpl.java:610)
at com.sun.xml.ws.server.WSEndpointImpl.initManagedObjectManager(WSEndpointImpl.java:591)
at com.sun.xml.ws.server.WSEndpointImpl.(WSEndpointImpl.java:121)
at com.sun.xml.ws.server.EndpointFactory.create(EndpointFactory.java:307)
at com.sun.xml.ws.server.EndpointFactory.create(EndpointFactory.java:302)
at com.sun.xml.ws.server.EndpointFactory.createEndpoint(EndpointFactory.java:134)
at com.sun.xml.ws.api.server.WSEndpoint.create(WSEndpoint.java:548)
at com.sun.xml.ws.api.server.WSEndpoint.create(WSEndpoint.java:530)
at com.sun.xml.ws.transport.http.server.EndpointImpl.createEndpoint(EndpointImpl.java:304)
at com.sun.xml.ws.transport.http.server.EndpointImpl.publish(EndpointImpl.java:217)

This does not happen on 2.4.1 which includes the missing classes (albeit in the package org.glassfish.gmbal.generic).

regards,
juraj

**Comment by jurajw** [comment]
What is the relation between this project and javaee/metro project? Asking because I have reported this issue as well as https://github.com/javaee/metro/issues/49, and looking in more detail, it seems that javaee/metro is effectively abandoned.

**Comment by borjafg** [comment]
Here is explained why that repository (and others) was archived: [Java EE moves to the Eclipse Foundation](https://blogs.eclipse.org/post/mike-milinkovich/java-ee-moves-eclipse-foundation). Basically "javaee/metro-jax-ws" and "eclipse-ee4j/metro-jax-ws" are the same project.

**Comment by jurajw** [comment]
The move to Eclipse I caught. Interestingly there is javaee/metro-jax-ws which is archived, and javaee/metro which is not (If you check my comment, I meant the later project). There are as well other javaee projects that are not archived.

**Comment by borjafg** [comment]
That is probably because the migration of these projects has not been completed.

A project of the "javaee organization" is archived only when the migration to the eclipse foundation has been completed.

**Comment by lukasj** [comment]
should be fixed by https://github.com/eclipse-ee4j/metro-wsit/pull/41
