### ISSUE TITLE
JAVA 11 - Illegal reflective access by com.sun.xml.ws.model.Injector

### ISSUE THREAD

**Issue by marcuswf** [eclipse-ee4j/metro-jax-ws#60]
Can you please have a look on this illegal reflective access when running on JAVA 11?

`WARNING: Illegal reflective access by com.sun.xml.ws.model.Injector (file:/C:/Users/XXXXXX/.m2/repository/com/sun/xml/ws/jaxws-rt/2.3.2/jaxws-rt-2.3.2.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
	at com.sun.xml.ws.model.Injector.getMethod(Injector.java:103)
	at com.sun.xml.ws.model.Injector.access$000(Injector.java:32)
	at com.sun.xml.ws.model.Injector$1.run(Injector.java:49)
	at com.sun.xml.ws.model.Injector$1.run(Injector.java:45)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.xml.ws.model.Injector.<clinit>(Injector.java:44)
	at com.sun.xml.ws.model.WrapperBeanGenerator.createRequestWrapperBean(WrapperBeanGenerator.java:265)
	at com.sun.xml.ws.model.RuntimeModeler.getRequestWrapperClass(RuntimeModeler.java:345)
	at com.sun.xml.ws.model.RuntimeModeler.processDocWrappedMethod(RuntimeModeler.java:771)
	at com.sun.xml.ws.model.RuntimeModeler.processMethod(RuntimeModeler.java:701)
	at com.sun.xml.ws.model.RuntimeModeler.processClass(RuntimeModeler.java:461)
	at com.sun.xml.ws.model.RuntimeModeler.buildRuntimeModel(RuntimeModeler.java:290)
	at com.sun.xml.ws.db.DatabindingImpl.<init>(DatabindingImpl.java:70)
	at com.sun.xml.ws.db.DatabindingProviderImpl.create(DatabindingProviderImpl.java:44)
	at com.sun.xml.ws.db.DatabindingProviderImpl.create(DatabindingProviderImpl.java:28)
	at com.sun.xml.ws.db.DatabindingFactoryImpl.createRuntime(DatabindingFactoryImpl.java:90)
	at com.sun.xml.ws.client.WSServiceDelegate.buildRuntimeModel(WSServiceDelegate.java:852)
	at com.sun.xml.ws.client.WSServiceDelegate.createSEIPortInfo(WSServiceDelegate.java:869)
	at com.sun.xml.ws.client.WSServiceDelegate.addSEI(WSServiceDelegate.java:832)
	at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:421)
	at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:390)
	at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:372)
	at javax.xml.ws.Service.getPort(Service.java:139)`

Here are the methods that this code is trying to make accessible:

 - protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError
- protected final void java.lang.ClassLoader.resolveClass(java.lang.Class)
- protected java.lang.Package java.lang.ClassLoader.getPackage(java.lang.String)
- protected java.lang.Package java.lang.ClassLoader.definePackage(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.net.URL)

**Comment by marcuswf** [comment]
If I set --illegal-access=deny, then it ends up on issue https://github.com/eclipse-ee4j/metro-jax-ws/issues/55 .
Therefore, after analyzing the source code, I believe this warning is an expected behavior if illegal access is set to be permitted.
