### ISSUE TITLE
java.io.FileNotFoundException: C:\Users\user\.mailcap (The system cannot find the file specified)

### ISSUE THREAD

**Issue by gavenkoa** [eclipse-ee4j/metro-jax-ws#643]
At some point the app started to fail with:

```
DEBUG  jakarta.activation  MailcapCommandMap: load HOME
DEBUG  jakarta.activation  Checking system property jakarta.activation.spi.MailcapRegistryProvider
DEBUG  jakarta.activation    not found
DEBUG  jakarta.activation  Using java.util.ServiceLoader to find jakarta.activation.spi.MailcapRegistryProvider
DEBUG  jakarta.activation  ServiceProvider loading Facility used; returning object [com.sun.activation.registries.MailcapRegistryProviderImpl]
DEBUG  jakarta.activation  new MailcapFile: file C:\Users\user\.mailcap
DEBUG  jakarta.activation  MailcapRegistry: can't load from file - C:\Users\user\.mailcap
java.io.FileNotFoundException: C:\Users\user\.mailcap (The system cannot find the file specified)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
	at java.base/java.io.FileReader.<init>(FileReader.java:60)
	at com.sun.activation.registries.MailcapFile.<init>(MailcapFile.java:61)
	at com.sun.activation.registries.MailcapRegistryProviderImpl.getByFileName(MailcapRegistryProviderImpl.java:29)
	at jakarta.activation.MailcapCommandMap.loadFile(MailcapCommandMap.java:284)
	at jakarta.activation.MailcapCommandMap.<init>(MailcapCommandMap.java:154)
	at jakarta.activation.CommandMap.getDefaultCommandMap(CommandMap.java:60)
	at com.sun.xml.ws.binding.BindingImpl.initializeJavaActivationHandlers(BindingImpl.java:163)
	at com.sun.xml.ws.binding.BindingImpl.createCodec(BindingImpl.java:155)
	at com.sun.xml.ws.client.Stub.createPipeline(Stub.java:316)
	at com.sun.xml.ws.client.Stub.<init>(Stub.java:279)
	at com.sun.xml.ws.client.Stub.<init>(Stub.java:212)
	at com.sun.xml.ws.client.Stub.<init>(Stub.java:227)
	at com.sun.xml.ws.client.sei.SEIStub.<init>(SEIStub.java:68)
	at com.sun.xml.ws.client.WSServiceDelegate.getStubHandler(WSServiceDelegate.java:806)
	at com.sun.xml.ws.client.WSServiceDelegate.createEndpointIFBaseProxy(WSServiceDelegate.java:795)
	at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:426)
	at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:392)
	at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:373)
	at jakarta.xml.ws.Service.getPort(Service.java:139)
```

I don't understand what is relation between `jakarta.xml.ws.Service.getPort()` and user specific `.mailcap` file.

**Comment by gavenkoa** [comment]
My dependencies:

```
mvn dependency:copy -Dartifact=com.sun.xml.ws:rt:4.0.0:pom -DoutputDirectory=.
mvn dependency:copy -Dartifact=com.sun.xml.ws:project:4.0.0:pom -DoutputDirectory=.
```

**Comment by gavenkoa** [comment]
It looks like the problem occurred when I ran same app second time so some kind of file locking happened in Windows 10.

Still my question is valid: why is `.mailcap` file influencing SOAP services functioning.
